# Generated by Django 4.2.20 on 2025-03-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_delete_education_delete_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=255)),
                ('Skills', models.CharField(max_length=255)),
                ('SoftSkills', models.CharField(max_length=255)),
                ('AdvancedConcepts', models.CharField(max_length=255)),
                ('Certifications', models.CharField(max_length=255)),
            ],
        ),
    ]
